language: go

go:
- "1.12"

services:
- docker

# Only clone the most recent commit.
git:
  depth: 1
jobs:
  include:
  - stage: test
    script: ./make.sh test
  - script: ./make.sh integration-test
  - script: ./make.sh static-analysis
  - stage: deploy
    if: branch = master
    script:
    - ./make.sh publish
    - ./make.sh deploy